@ObligatorioAPI_HostAddress = http://localhost:5167

GET {{ObligatorioAPI_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{ObligatorioAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
