CREATE USER IF NOT EXISTS 'db_auth'@'%' IDENTIFIED BY 'contra-grupo10';
CREATE USER IF NOT EXISTS 'db_usuario'@'%' IDENTIFIED BY 'contra-grupo10';
CREATE USER IF NOT EXISTS 'db_usuario_lectura'@'%' IDENTIFIED BY 'contra-grupo10';
CREATE USER IF NOT EXISTS 'db_funcionario'@'%' IDENTIFIED BY 'contra-grupo10';
CREATE USER IF NOT EXISTS 'db_administrador'@'%' IDENTIFIED BY 'contra-grupo10';
CREATE USER IF NOT EXISTS 'db_administrador_lectura'@'%' IDENTIFIED BY 'contra-grupo10';

GRANT SELECT, INSERT ON ticketing2026.Documento TO 'db_auth'@'%';
GRANT SELECT, INSERT ON ticketing2026.Direccion TO 'db_auth'@'%';
GRANT SELECT, INSERT ON ticketing2026.Usuario TO 'db_auth'@'%';
GRANT SELECT ON ticketing2026.Administrador TO 'db_auth'@'%';
GRANT SELECT ON ticketing2026.Funcionario TO 'db_auth'@'%';
GRANT SELECT, INSERT ON ticketing2026.UsuarioGeneral TO 'db_auth'@'%';

GRANT SELECT ON ticketing2026.Pais TO 'db_usuario'@'%';
GRANT SELECT, INSERT ON ticketing2026.Documento TO 'db_usuario'@'%';
GRANT SELECT, INSERT ON ticketing2026.Direccion TO 'db_usuario'@'%';
GRANT SELECT, INSERT, UPDATE ON ticketing2026.Usuario TO 'db_usuario'@'%';
GRANT SELECT, INSERT, UPDATE ON ticketing2026.Telefono TO 'db_usuario'@'%';
GRANT SELECT, INSERT ON ticketing2026.UsuarioGeneral TO 'db_usuario'@'%';
GRANT SELECT ON ticketing2026.Estadio TO 'db_usuario'@'%';
GRANT SELECT ON ticketing2026.Sector TO 'db_usuario'@'%';
GRANT SELECT ON ticketing2026.Equipo TO 'db_usuario'@'%';
GRANT SELECT ON ticketing2026.Evento TO 'db_usuario'@'%';
GRANT SELECT ON ticketing2026.EventoHabilitaSector TO 'db_usuario'@'%';
GRANT SELECT ON ticketing2026.Comision TO 'db_usuario'@'%';
GRANT SELECT, INSERT ON ticketing2026.Compra TO 'db_usuario'@'%';
GRANT SELECT, INSERT ON ticketing2026.CompraAplicaComision TO 'db_usuario'@'%';
GRANT SELECT, INSERT ON ticketing2026.Entrada TO 'db_usuario'@'%';
GRANT SELECT, INSERT, UPDATE ON ticketing2026.Transferencia TO 'db_usuario'@'%';
GRANT SELECT, INSERT ON ticketing2026.TransferenciaContieneEntrada TO 'db_usuario'@'%';

GRANT SELECT ON ticketing2026.Pais TO 'db_usuario_lectura'@'%';
GRANT SELECT ON ticketing2026.Documento TO 'db_usuario_lectura'@'%';
GRANT SELECT ON ticketing2026.Direccion TO 'db_usuario_lectura'@'%';
GRANT SELECT ON ticketing2026.Usuario TO 'db_usuario_lectura'@'%';
GRANT SELECT ON ticketing2026.Telefono TO 'db_usuario_lectura'@'%';
GRANT SELECT ON ticketing2026.UsuarioGeneral TO 'db_usuario_lectura'@'%';
GRANT SELECT ON ticketing2026.Estadio TO 'db_usuario_lectura'@'%';
GRANT SELECT ON ticketing2026.Sector TO 'db_usuario_lectura'@'%';
GRANT SELECT ON ticketing2026.Equipo TO 'db_usuario_lectura'@'%';
GRANT SELECT ON ticketing2026.Evento TO 'db_usuario_lectura'@'%';
GRANT SELECT ON ticketing2026.EventoHabilitaSector TO 'db_usuario_lectura'@'%';
GRANT SELECT ON ticketing2026.Comision TO 'db_usuario_lectura'@'%';
GRANT SELECT ON ticketing2026.Compra TO 'db_usuario_lectura'@'%';
GRANT SELECT ON ticketing2026.CompraAplicaComision TO 'db_usuario_lectura'@'%';
GRANT SELECT ON ticketing2026.Entrada TO 'db_usuario_lectura'@'%';
GRANT SELECT ON ticketing2026.Transferencia TO 'db_usuario_lectura'@'%';
GRANT SELECT ON ticketing2026.TransferenciaContieneEntrada TO 'db_usuario_lectura'@'%';

GRANT SELECT ON ticketing2026.Pais TO 'db_funcionario'@'%';
GRANT SELECT ON ticketing2026.Documento TO 'db_funcionario'@'%';
GRANT SELECT ON ticketing2026.Direccion TO 'db_funcionario'@'%';
GRANT SELECT ON ticketing2026.Usuario TO 'db_funcionario'@'%';
GRANT SELECT ON ticketing2026.Telefono TO 'db_funcionario'@'%';
GRANT SELECT ON ticketing2026.UsuarioGeneral TO 'db_funcionario'@'%';
GRANT SELECT ON ticketing2026.Estadio TO 'db_funcionario'@'%';
GRANT SELECT ON ticketing2026.Sector TO 'db_funcionario'@'%';
GRANT SELECT ON ticketing2026.Equipo TO 'db_funcionario'@'%';
GRANT SELECT ON ticketing2026.Evento TO 'db_funcionario'@'%';
GRANT SELECT ON ticketing2026.EventoHabilitaSector TO 'db_funcionario'@'%';
GRANT SELECT ON ticketing2026.Funcionario TO 'db_funcionario'@'%';
GRANT SELECT ON ticketing2026.FuncionarioTrabajaEstadio TO 'db_funcionario'@'%';
GRANT SELECT ON ticketing2026.FuncionarioAsignadoEventoSector TO 'db_funcionario'@'%';
GRANT SELECT ON ticketing2026.Compra TO 'db_funcionario'@'%';
GRANT SELECT, UPDATE ON ticketing2026.Entrada TO 'db_funcionario'@'%';
GRANT SELECT, UPDATE ON ticketing2026.TokenQR TO 'db_funcionario'@'%';
GRANT INSERT ON ticketing2026.Verificacion TO 'db_funcionario'@'%';
GRANT SELECT ON ticketing2026.Escaner TO 'db_funcionario'@'%';
GRANT SELECT ON ticketing2026.FuncionarioEscaner TO 'db_funcionario'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.Pais TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.Documento TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.Direccion TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.Usuario TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.Telefono TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.UsuarioGeneral TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.Estadio TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.Sector TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.Equipo TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.Evento TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.EventoHabilitaSector TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.Funcionario TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.FuncionarioTrabajaEstadio TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.FuncionarioAsignadoEventoSector TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.Comision TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.Compra TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.CompraAplicaComision TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.Entrada TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.Transferencia TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.TransferenciaContieneEntrada TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.Escaner TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.FuncionarioEscaner TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.TokenQR TO 'db_administrador'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ticketing2026.Verificacion TO 'db_administrador'@'%';

GRANT SELECT ON ticketing2026.Pais TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.Documento TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.Direccion TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.Usuario TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.Telefono TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.UsuarioGeneral TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.Estadio TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.Sector TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.Equipo TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.Evento TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.EventoHabilitaSector TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.Funcionario TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.FuncionarioTrabajaEstadio TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.FuncionarioAsignadoEventoSector TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.Comision TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.Compra TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.CompraAplicaComision TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.Entrada TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.Transferencia TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.TransferenciaContieneEntrada TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.Escaner TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.FuncionarioEscaner TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.TokenQR TO 'db_administrador_lectura'@'%';
GRANT SELECT ON ticketing2026.Verificacion TO 'db_administrador_lectura'@'%';
